// frontend/app/changelog/page.tsx
import Markdown from "@/components/markdown"

import data from "./data"

export default async function ChangelogPage() {
  const { changelog } = await data()

  return (
    <main className="mx-auto flex flex-col px-3 py-6 sm:py-12 w-full max-w-2xl gap-4 sm:gap-2">
      <h1 className="text-4xl mb-2 sm:text-6xl sm:mb-4 font-semibold text-neutral-1 dark:text-neutral+1">
        Changelog
      </h1>
      <Markdown content={changelog} />
    </main>
  )
}

// frontend/src/routes/(pages)/changelog/+page.svelte
<script lang="ts">
	import type { PageData } from "./$types"
	import H1 from "$lib/elements/h1.svelte"
	import Card from "$lib/components/card.svelte"
	import Markdown from "$lib/markdown/markdown.svelte"

	export let data: PageData
</script>

<svelte:head>
	<title>Changelog</title>
</svelte:head>

<div class="flex flex-col gap-4 w-full max-w-3xl mx-auto">
	<div class="mb-4 mt-8">
		<H1>Changelog</H1>
	</div>
	{#each data.props.changelogs as changelog}
		<Card>
			<Markdown source={changelog.markdown} />
		</Card>
	{/each}
</div>
