// frontend/app/profiles/[username]/page.tsx
import api from "@/lib/api"
import { User, Blog, Post, Profile } from "@/models"
import PostCollection from "@/components/post-collection"
import MemberCard from "@/components/member-card"

import data from "./data"

interface Props {
  params: {
    username: string
  }
}

export default async function ProfilePage({ params }: Props) {
  const { profile, user, blogs, posts, likes } = await data(params.username)

  return (
    <main className="mx-auto my-8 flex flex-col items-center sm:flex-row sm:items-start px-2 w-full max-w-6xl gap-4 sm:gap-16">
      <MemberCard profile={profile} user={user} blogs={blogs} />

      <div>
        <div>
          <div className="py-4">
            <h1 className="font-semibold">Posts by {profile.displayName}</h1>
          </div>
          <PostCollection posts={posts} />
        </div>
        <div>
          <div className="py-4">
            <h1 className="font-semibold">Liked by {profile.displayName}</h1>
          </div>
          <PostCollection posts={likes} />
        </div>
      </div>
    </main>
  )
}

// frontend/src/routes/profiles/[username]/+page.svelte
<script lang="ts">
	import type { PageData } from "./$types"
	import Main from "$lib/layouts/main.svelte"
	import ProfilePreview from "$lib/components/profile-preview/profile-preview.svelte"
	import Column from "$lib/layouts/column.svelte"
	import Preview from "$lib/components/entry-preview/preview.svelte"
	import Title from "$lib/entry/preview/segments/title.svelte"
	import Date from "$lib/entry/preview/segments/date.svelte"
	import Blog from "$lib/entry/preview/segments/blog.svelte"
	export let data: PageData

	let { profile, user, entries } = data.props
</script>

<Main>
	<div class="flex flex-col sm:flex-row gap-8">
		<div class="mx-auto sm:mx-0">
			<ProfilePreview {profile} {user} />
		</div>

		<div class="flex flex-col gap-4">
			<h2 class="text-2xl sm:text-4xl font-semibold leading-tight text-zinc-900">Blog Posts</h2>
			<Column>
				{#each entries as { title, blogName, blogSlug, postSlug, createdAt }}
					<Preview>
						<Blog slot="blog" {blogName} {blogSlug} />
						<Title slot="title" {title} {blogSlug} {postSlug} />
						<Date slot="date" date={createdAt} />
					</Preview>
				{/each}
			</Column>
		</div>
	</div>
</Main>
