// frontend/components/likes/likes.tsx
"use client"

import { useState } from "react"

import { HeartIcon, HeartFilledIcon } from "@radix-ui/react-icons"

import Button from "@/components/button"
import Counter from "@/components/counter"

interface Props {
	initialCount: number
}

export default function Likes({ initialCount }: Props) {
	const active = true

	const [isLiked, setIsLiked] = useState(false)
	const [count, setCount] = useState(initialCount)

	const onClick = () => {
		if (isLiked) {
			setIsLiked(false)
			setCount(count - 1)
		} else {
			setIsLiked(true)
			setCount(count + 1)
		}
	}

	// The Likes component is non-interactive if the user is not logged in.
	if (!active) {
		return (
			<div className="flex flex-row gap-1 items-center justify-center px-2 py-0.5 rounded-md select-none group">
				<span>
					<HeartIcon className="text-neutral-low dark:text-neutral-light h-4 aspect-square" />
				</span>
				<span className="text-sm font-medium w-7 flex flex-col items-end">
					<Counter count={count} />
				</span>
			</div>
		)
	}

	return (
		<Button onClick={onClick} variant={{ intent: "secondary" }}>
			<div className="flex flex-row gap-1 items-center justify-center rounded-md select-none group">
				<span>
					{isLiked ? (
						<HeartFilledIcon className="text-neutral-low dark:text-neutral-light h-4 aspect-square" />
					) : (
						<HeartIcon className="text-neutral-low dark:text-neutral-light h-4 aspect-square" />
					)}
				</span>
				<span className="w-7 flex flex-col items-end">
					<Counter count={count} />
				</span>
			</div>
		</Button>
	)
}

// archive/devy-frontend/src/lib/components/likes.svelte
<script lang="ts">
	import Heart from "$lib/icons/heart.svelte"
	import HeartFilled from "$lib/icons/heart-filled.svelte"

	import { getLikes } from "$lib/state/likes.svelte"
	import { getSession } from "$lib/state/session.svelte"

	const likesState = getLikes()
	const session = getSession()

	const { entryId, likeCount }: { entryId: string; likeCount: number } = $props()

	likesState.setCount(entryId, likeCount)
	let count = $derived(likesState.getCount(entryId))
	let isLiked = $derived(likesState.isLiked(entryId))

	const onclick = async () => {
		await likesState.toggle(entryId)
	}
</script>

{#if session.isAuthenticated}
	<button class="group mr-2 flex flex-row items-center justify-start gap-1.5 text-sm" {onclick}>
		{#if isLiked}
			<div
				class="aspect-square w-4 text-stone-900 transition-all group-hover:-translate-y-1.5 group-hover:rotate-12 group-hover:scale-110 group-hover:text-red-500 dark:text-zinc-100"
			>
				<HeartFilled />
			</div>
		{:else}
			<div
				class="aspect-square w-4 text-stone-500 transition-all group-hover:-translate-y-1.5 group-hover:rotate-12 group-hover:scale-110 group-hover:text-red-500 dark:text-zinc-200"
			>
				<Heart />
			</div>
		{/if}

		<span class="flex w-8 flex-row justify-start font-medium text-stone-700 dark:text-zinc-300"
			>{count}</span
		>
	</button>
{:else}
	<div class="mr-2 flex select-none flex-row items-center justify-start gap-1.5 text-sm">
		<div class="aspect-square w-4 text-stone-500">
			<Heart />
		</div>
		<span class="flex w-8 flex-row justify-start font-medium text-stone-700 dark:text-zinc-200"
			>{count}</span
		>
	</div>
{/if}
