// archive/devy-frontend/src/routes/menu.svelte
<script lang="ts">
	import { cva } from "cva"
	import { createDropdownMenu, melt } from "@melt-ui/svelte"
	import HamburgerMenu from "$lib/icons/hamburger-menu.svelte"

	const {
		elements: { menu, item, trigger }
	} = createDropdownMenu({ positioning: { placement: "bottom-end" } })

	let button = cva([
		"rounded",
		"border",
		"p-1",
		"text-stone-600",
		"transition-all",
		"hover:text-stone-950",
		"dark:text-zinc-300",
		"dark:hover:text-zinc-100",
		"data-[state=open]:border-stone-200/70",
		"data-[state=open]:bg-white",
		"data-[state=open]:shadow",
		"data-[state=open]:dark:border-zinc-600/70",
		"data-[state=open]:dark:bg-zinc-800",
		"data-[state=open]:dark:shadow-none",
		"data-[state=closed]:border-transparent",
		"data-[state=closed]:bg-none",
		"data-[state=closed]:hover:bg-stone-200",
		"data-[state=closed]:dark:hover:bg-zinc-800"
	])
	let section = cva([
		"w-56",
		"sm:w-40",
		"rounded-md",
		"border",
		"border-stone-200",
		"bg-white",
		"dark:border-zinc-700",
		"dark:bg-zinc-700",
		"py-1",
		"flex",
		"flex-col",
		"gap-1",
		"shadow-lg",
		"dark:shadow-none"
	])
	let menuItem = cva([
		"sm:text-sm",
		"font-medium",
		"text-stone-600",
		"dark:text-zinc-300",
		"mx-1",
		"px-2",
		"py-1",
		"sm:py-0.5",
		"group",
		"flex",
		"flex-row",
		"rounded",
		"items-center",
		"pointer-cursor",
		"justify-between",
		"hover:bg-stone-200/50",
		"dark:hover:bg-zinc-800/70",
		"hover:text-stone-950",
		"dark:hover:text-zinc-100",
		"transition-all"
	])
</script>

{#snippet divider()}
	<span class="w-full border-b border-b-stone-200"></span>
{/snippet}

<button use:melt={$trigger} class={button()}><HamburgerMenu /></button>

<section use:melt={$menu} class={section()}>
	<a href="/changelog" use:melt={$item} class={menuItem()}>Changelog</a>
	<a href="/docs" use:melt={$item} class={menuItem()}>Documentation</a>
	<a href="/feedback" use:melt={$item} class={menuItem()}>Feedback</a>
</section>

// frontend/components/menu/menu.tsx
"use client"

// This component is based on RadixUI's DropdownMenu component.
// https://www.radix-ui.com/primitives/docs/components/dropdown-menu

import * as DropdownMenu from "@radix-ui/react-dropdown-menu"

import Link from "@/components/link"

type Relation = "below-aligned-left"

type SeparatorItem = { type: "separator" }
type LinkItem = {
	type: "link"
	label: string
	tag?: string
	href: string
}
type ButtonItem = {
	type: "button"
	label: string
	tag?: string
	onClick: () => void
}
export type Item = SeparatorItem | LinkItem | ButtonItem

interface Props {
	icon: React.ReactNode
	ariaLabel: string
	relation: Relation
	items: Item[]
	initialIsOpen?: boolean
}

export default function Menu({ icon, ariaLabel, items, initialIsOpen }: Props) {
	return (
		<DropdownMenu.Root defaultOpen={initialIsOpen}>
			<DropdownMenu.Trigger asChild>
				<button className={trigger} aria-label={ariaLabel}>
					{icon}
				</button>
			</DropdownMenu.Trigger>

			<DropdownMenu.Portal>
				<DropdownMenu.Content
					className={content}
					sideOffset={5}
					align="end"
				>
					{items.map((item, index) => (
						<Item key={index} item={item} />
					))}
				</DropdownMenu.Content>
			</DropdownMenu.Portal>
		</DropdownMenu.Root>
	)
}

const trigger = [
	"text-neutral-2",
	"dark:text-neutral+2",
	"inline-flex",
	"items-center",
	"rounded",
	"p-1",

	"hover:bg-neutral+1",
	"hover:dark:bg-neutral-1",

	"data-[state=open]:bg-neutral+3",
	"data-[state=open]:text-neutral-3",
	"data-[state=open]:ring-1",
	"data-[state=open]:ring-neutral+1",

	"data-[state=open]:dark:bg-neutral-3",
	"data-[state=open]:dark:text-neutral+2",
	"data-[state=open]:dark:ring-1",
	"data-[state=open]:dark:ring-neutral-1",

	"data-[state=open]:shadow",
].join(" ")
const content = [
	"w-48",
	"rounded-md",
	"border",

	"border-neutral+1",
	"text-neutral-2",
	"bg-neutral+3",

	"dark:border-neutral-1",
	"dark:text-neutral+2",
	"dark:bg-neutral-3",

	"data-[side=top]:animate-slideDownAndFade",
	"data-[side=right]:animate-slideLeftAndFade",
	"data-[side=bottom]:animate-slideUpAndFade",
	"data-[side=left]:animate-slideRightAndFade",
].join(" ")

const Item = ({ item }: { item: Item }) => {
	switch (item.type) {
		case "separator":
			return (
				<DropdownMenu.Separator className="my-1 border-b border-neutral+1 dark:border-neutral-1" />
			)
		case "link":
			return (
				<DropdownMenu.Item asChild>
					<Link
						href={item.href}
						className={menuItem}
						variant={{ underline: false, styled: false }}
					>
						<span>{item.label}</span>
						{item.tag && <span className={pill}>{item.tag}</span>}
					</Link>
				</DropdownMenu.Item>
			)
		case "button":
			return (
				<DropdownMenu.Item asChild>
					<button className={menuItem} onClick={item.onClick}>
						<span>{item.label}</span>
						{item.tag && <span className={pill}>{item.tag}</span>}
					</button>
				</DropdownMenu.Item>
			)
	}
}

const menuItem = [
	"mx-1",
	"my-1",
	"px-2",
	"py-0.5",

	"outline-none",
	"transition-all",
	"group",
	"text-sm",
	"rounded",
	"flex",
	"flex-row",
	"items-center",
	"justify-between",
	"pointer-cursor",

	"data-[highlighted]:bg-neutral+1",
	"data-[highlighted]:dark:bg-neutral-1",

	"hover:bg-neutral+1",
	"hover:dark:bg-neutral-1",
].join(" ")
const pill = [
	"px-1.5",
	"py-0.5",
	"text-xs",
	"rounded-full",
	"border",

	"border-neutral+1",
	"bg-neutral+1",

	"dark:border-neutral-1",
	"dark:bg-neutral-1",

	"group-hover:bg-neutral+1",
	"group-hover:border-neutral+2",

	"group-hover:dark:bg-neutral-1",
	"group-hover:dark:border-neutral-2",
].join(" ")
