// frontend/src/lib/components/nav.svelte
<script lang="ts">
	import ProfileToken from "./profile-token.svelte"
	import Menu from "$lib/components/menu"
	import { getSessionState } from "$lib/state/session.svelte"

	const sessionState = getSessionState()
</script>

<nav class="flex flex-row items-center gap-1">
	{#if sessionState.session}
		<ProfileToken
			username={sessionState.session.username}
			displayName={sessionState.session.displayName}
			avatarUrl={sessionState.session.avatarUrl}
		/>
	{:else}
		<a
			href="/auth/sign-in"
			class="px-2 py-0.5 text-sm font-medium text-stone-600 hover:text-stone-950 hover:bg-stone-100 rounded-full transition"
			>Sign in</a
		>
	{/if}

	<div>
		<Menu>
			<Menu.Link href="/feedback">Feedback</Menu.Link>
			<Menu.Link href="/changelog">Changelog</Menu.Link>

			{#if sessionState.session}
				<Menu.Sep />
				<Menu.Button onclick={sessionState.signOut()}>Sign out</Menu.Button>
			{/if}
		</Menu>
	</div>
</nav>

// frontend/components/dynamic/Nav/Nav.tsx
"use client"

import { GitHubLogoIcon } from "@radix-ui/react-icons"

import { Link } from "@/components/elements"

import Menu from "./Menu"
import useSession from "@/auth/useSession"
import type Session from "@/auth/Session"
import Avatar from "@/components/elements/Avatar"

export default function Nav() {
	const { session } = useSession()

	return (
		<nav className="flex flex-row gap-2">
			{session ? <Token session={session} /> : <Login />}
			<Menu />
		</nav>
	)
}

const Login = () => (
	<Link href="/api/auth/login" prefetch={false}>
		<div className="pl-2 pr-2 py-0.5 flex flex-row rounded-l-full gap-2 items-center transition-all">
			<GitHubLogoIcon className="w-4 h-4" />
			<span className="text-xs font-medium">Sign in</span>
		</div>
	</Link>
)

const Token = ({ session }: { session: Session }) => (
	<Link href={`/profiles/${session.user.username}`}>
		<div className="pl-2 pr-2 py-0.5 flex flex-row rounded-l-full gap-2 items-center transition-all">
			<Avatar
				displayName={session.profile.displayName}
				avatarUrl={session.profile.avatarUrl}
				className="w-4 h-4"
			/>
			<span className="text-sm font-medium">
				{session.profile.displayName}
			</span>
		</div>
	</Link>
)
