// site/src/lib/post/preview/preview.svelte
<script lang="ts">
	import type { Post } from "$lib/types"
	import Json from "$lib/utils/json.svelte"
	import { Slash } from "radix-icons-svelte"
	import H2 from "$lib/element/h2.svelte"
	import Like from "$lib/post/like/like.svelte"
	import RelativeDate from "$lib/utils/relative-date.svelte"

	export let post: Post
	const { title, slug, authorName, authorUsername, blogName, blogSlug, createdAt } = post
</script>

<div class="grid grid-rows-3 grid-cols-[max-content_1fr] gap-x-4 auto-rows-min">
	<div class="col-start-1 row-start-2 w-10 flex flex-row justify-end">
		<Like {post} />
	</div>
	<div class="col-start-2 col-span-3 row-start-1 flex flex-row items-end gap-0.5 text-xs">
		<a href={`/profiles/${authorUsername}`} class="text-zinc-600">{authorName}</a>
		<Slash class="text-zinc-500" />
		<a href={"#"} class="text-zinc-600">{blogName}</a>
	</div>
	<div class="col-start-2 col-span-3 row-start-2 font-medium">
		<H2><a href={`/${blogSlug}/${slug}`}>{title}</a></H2>
	</div>
	<div class="col-start-2 col-span-3 row-start-3 text-xs"><RelativeDate date={createdAt} /></div>
</div>

// frontend/components/post/preview/preview.tsx
import Post from "@/models/Post"
import Link from "@/components/elements/link"
import Likes from "@/components/post/likes"
import RelativeDate from "@/components/utils/relative-date"

interface Props {
	post: Post
}

export default function Preview({ post }: Props) {
	return (
		<section className={wrapper}>
			<div className="grid grid-rows-3 grid-cols-[max-content_1fr] gap-x-8">
				<div className="col-start-2 col-span-3 row-start-2">
					<Link
						href={{
							pathname: `/${post.blogSlug}/${post.slug}`,
						}}
						className="font-medium text-zinc-50"
						variant={{ underline: false, styled: false }}
					>
						{post.title}
					</Link>
				</div>
				<div className="w-8 col-start-1 row-start-2">
					<Likes
						postId={post.id}
						title={post.title}
						initialCount={post.likes}
					/>
				</div>

				<div className="text-xs flex items-center justify-start gap-2 col-start-2 col-span-3">
					<Link
						href={{ pathname: `/${post.blogSlug}` }}
						variant={{ underline: false, styled: false }}
						className="text-neutral hover:text-neutral-1 hover:dark:text-neutral+1"
						aria-label={`View blog ${post.blogName}`}
					>
						{post.blogName}
					</Link>
					<RelativeDate
						date={post.createdAt}
						className="text-neutral select-none"
					/>
				</div>

				<div className="flex flex-row gap-2 col-start-2 col-span-3 row-start-3 items-baseline text-xs">
					<Link
						href={{
							pathname: `/profiles/${post.authorUsername}`,
						}}
						variant={{ underline: false, styled: false }}
						aria-label={`View ${post.authorName}'s profile`}
					>
						{post.authorName}
					</Link>
				</div>
			</div>
		</section>
	)
}

const wrapper = ["py-1", "px-4", "w-full", "transition-all"].join(" ")
