// frontend/app/profiles/[username]/page.tsx
import api from "@/lib/api"
import { User, Blog, Post, Profile } from "@/models"
import PostCollection from "@/components/post-collection"
import MemberCard from "@/components/member-card"

import data from "./data"

interface Props {
  params: {
    username: string
  }
}

export default async function ProfilePage({ params }: Props) {
  const { profile, user, blogs, posts, likes } = await data(params.username)

  return (
    <main className="mx-auto my-8 flex flex-col items-center sm:flex-row sm:items-start px-2 w-full max-w-6xl gap-4 sm:gap-16">
      <MemberCard profile={profile} user={user} blogs={blogs} />

      <div>
        <div>
          <div className="py-4">
            <h1 className="font-semibold">Posts by {profile.displayName}</h1>
          </div>
          <PostCollection posts={posts} />
        </div>
        <div>
          <div className="py-4">
            <h1 className="font-semibold">Liked by {profile.displayName}</h1>
          </div>
          <PostCollection posts={likes} />
        </div>
      </div>
    </main>
  )
}

// site/src/routes/profiles/[username]/+page.svelte
<script lang="ts">
	import type { PageData } from "./$types"
	import Main from "$lib/layouts/main.svelte"
	import CallingCard from "$lib/components/calling-card/calling-card.svelte"
	import Preview from "$lib/entry/preview/preview.svelte"
	import Column from "$lib/layouts/column.svelte"
	export let data: PageData

	let { blogs, profile, user, entries } = data.props
</script>

<Main>
	<div class="flex flex-col sm:flex-row gap-8">
		<CallingCard {blogs} {profile} {user} />
		<Column>
			{#each entries as entry}
				<Preview {entry} />
			{/each}
		</Column>
	</div>
</Main>
