// devy/components/models/Post/Preview.tsx
import Link from "next/link"
import { Heart, Bookmark } from "lucide-react"

import Post from "@/models/Post"

interface Props extends Post {}

export default function Preview(post: Props) {
	return (
		<div className="flex flex-row items-start gap-3">
			<div className="flex flex-col items-end text-slate-500">
				<div className="flex flex-row gap-1 items-center">
					<span className="text-sm text-slate-700">{post.likes}</span>
					<Heart className="w-4 aspect-square" />
				</div>
				<div>
					<Bookmark className="w-4 aspect-square" />
				</div>
			</div>
			<div className="flex flex-col">
				<Link
					href={`/${post.blog.slug}/${post.slug}`}
					className="hover:underline transition-all"
				>
					<h1 className="font-medium">{post.title}</h1>
				</Link>
				<div className="flex flex-row gap-2 text-sm">
					<Link href={`/profiles/${post.author.username}`}>
						{post.author.displayName}
					</Link>
					<span className="text-slate-600">
						{new Date(post.published).toDateString()}
					</span>
				</div>
				<div className="flex flex-row gap-2 mt-1">
					{post.tags.map((tag, id) => (
						<Link
							href={`/tags/${tag}`}
							key={id}
							className="uppercase text-xs px-1.5 py-0.25 rounded-lg border border-slate-300"
						>
							{tag}
						</Link>
					))}
				</div>
			</div>
		</div>
	)
}

// site/src/lib/entry/preview/preview.svelte
<script lang="ts">
	import type { Entry } from "$lib/types"
	import RelativeDate from "$lib/utils/relative-date.svelte"
	import { Heart, Bookmark } from "radix-icons-svelte"

	export let entry: Entry
	const { postSlug, title, blogSlug, blogName, authorName, authorSlug, likes, createdAt } = entry
</script>

<div class="grid grid-cols-10 max-w-xl">
	<div class="col-start-1 row-start-2">
		<button class="text-sm flex flex-row items-center gap-1 group"
			><Heart
				class="w-4 aspect-square text-zinc-500 group-hover:-translate-y-1 transition-all group-hover:rotate-12 group-hover:scale-110"
			/>{likes}</button
		>
	</div>
	<div class="col-start-2 row-start-1 col-span-9 -mb-0.5">
		<a href={`${blogSlug}`} class="text-xs text-zinc-500">{blogName}</a>
	</div>
	<div class="col-start-2 row-start-2 col-span-9">
		<a href={`${blogSlug}/${postSlug}`} class="font-medium">{title}</a>
	</div>
	<div class="col-start-2 row-start-3 flex flex-row gap-2 col-span-9">
		<a href={`/profiles/${authorSlug}`} class="text-xs text-zinc-500">{authorName}</a>
		<div class="text-xs"><RelativeDate date={createdAt} /></div>
		<button class="rounded group"
			><Bookmark
				class="w-4 aspect-square text-zinc-500 group-hover:-translate-y-1 group-hover:text-zinc-950 transition-all"
			/></button
		>
	</div>
</div>
