// site/src/lib/components/footer/footer.svelte
<footer class="w-full transition-all py-12">
	<div class="mx-auto max-w-6xl flex flex-row items-start">
		<div class="p-3 pb-12 bg-zinc-200/40 dark:bg-zinc-900/40 rounded-xl">
			<div class="flex flex-row gap-2 items-baseline mb-2">
				<a href="/" class="px-0.5 -ml-0.5 font-medium">Devy</a>
				<span
					class="text-xs font-medium px-2 py-0.5 rounded-full text-white bg-amber-600 dark:text-zinc-100 dark:bg-zinc-800 select-none"
					>Preview</span
				>
			</div>
			<div class="pt-2 flex flex-col sm:flex-row gap-12 text-sm text-zinc-800 dark:text-zinc-300">
				<section class="w-full sm:w-56 flex flex-col gap-4">
					<p>
						Devy is an open source platform for people to publish blog posts in markdown from their
						GitHub repositories.{" "}
					</p>
					<p>Thank you for checking it out.</p>
					<span class="self-end">
						&#8212;{" "}
						<a href="https://thomaseckert.dev">Thomas Eckert</a>
					</span>
				</section>
			</div>
		</div>
	</div>
</footer>

// frontend/app/footer.tsx
import Link from "@/components/link"
import Logomark from "@/components/logomark"

export default function Footer() {
  return (
    <footer className="w-full bg-neutral+2 dark:bg-neutral-3">
      <div className="mx-auto max-w-6xl px-2 pt-8 pb-44">
        <div className="w-56 pb-2 border-b border-b-zinc-700 flex flex-row gap-2 items-baseline">
          <Link href="/" variant={{ underline: false }}>
            <Logomark />
          </Link>
          <span className="text-xs font-medium px-2 py-0.5 rounded-full text-neutral-1 bg-neutral+1 dark:text-neutral+2 dark:bg-neutral-1 select-none">
            Preview
          </span>
        </div>

        <div className="pt-2 flex flex-row gap-12 text-sm text-zinc-300">
          <section className="w-56 flex flex-col gap-4">
            <p>
              Devy is an open source platform for people to publish blog posts
              in markdown from their GitHub repositories.{" "}
            </p>
            <p>Thank you for checking it out.</p>
            <span className="self-end">
              &#8212;{" "}
              <Link
                href="https://thomaseckert.dev"
                variant={{ underline: false }}
              >
                Thomas Eckert
              </Link>
            </span>
          </section>

          <section className="flex flex-col gap-1 items-start">
            <Link
              href="/changelog"
              className="font-medium"
              variant={{ underline: false }}
            >
              Changelog
            </Link>
            <Link
              href="https://github.com/t-eckert/devy"
              className="font-medium"
              variant={{ underline: false }}
            >
              Repo
            </Link>
          </section>
        </div>
      </div>
    </footer>
  )
}
