// apps/devy-app/src/routes/footer.svelte
<script lang="ts">
	import Logo from "$lib/components/logo.svelte";
	import Bounded from "$lib/layouts/bounded.svelte";

	let props = $props();
</script>

{#snippet item(href: string, text: string)}
	<li>
		<a
			{href}
			class="transition-color text-sm font-medium text-stone-600 hover:text-stone-950 dark:text-zinc-500 dark:hover:text-zinc-200"
			>{text}</a
		>
	</li>
{/snippet}

<footer
	class="h-full min-h-[90vh] border-t border-t-stone-200 bg-stone-100 dark:border-t-zinc-700 dark:bg-zinc-800"
>
	<Bounded>
		<div class="mt-24 flex h-full flex-col items-center gap-4">
			<section class="grid w-full flex-1 grid-cols-4 gap-6">
				<div>
					<div class="mb-2"><Logo height={42} /></div>
					<p class="text-sm">
						Devy lets you create a blog from a GitHub repo, push markdown to that repo, and publish
						that markdown as blog posts.
					</p>
				</div>
				<div class="text-sm">
					<h2 class="font-medium">Devy</h2>
					<ul>
						{@render item("/about", "About")}
						{@render item("/changelog", "Changelog")}
					</ul>
				</div>
				<div>
					<ul></ul>
				</div>
				<div>
					<ul></ul>
				</div>
			</section>
			<div class="text-sm text-stone-700"><code>v2024.11.28</code></div>
		</div>
	</Bounded>
</footer>

// frontend/app/footer.tsx
import Link from "@/components/link"
import Logomark from "@/components/logomark"

export default function Footer() {
  return (
    <footer className="w-full dark:bg-neutral-darkest">
      <div className="mx-auto max-w-6xl px-2 pt-8 pb-44">
        <div className="w-56 pb-2 border-b border-b-zinc-700 flex flex-row gap-2 items-baseline">
          <Link href="/">
            <Logomark />
          </Link>
        </div>

        <div className="pt-2 flex flex-row gap-12 text-sm text-zinc-300">
          <section className="w-56 flex flex-col gap-4">
            <p>
              Devy is an open source platform for people to publish blog posts
              in markdown from their GitHub repositories.{" "}
            </p>
            <p>Thank you for checking it out.</p>
            <span className="self-end">
              &#8212; <Link href="https://thomaseckert.dev">Thomas Eckert</Link>
            </span>
          </section>

          <section className="flex flex-col gap-1 items-start">
            <Link href="/changelog" className="font-medium">
              Changelog
            </Link>
            <Link
              href="https://github.com/t-eckert/devy"
              className="font-medium"
            >
              Repo
            </Link>
          </section>
        </div>
      </div>
    </footer>
  )
}
