// frontend/app/profiles/[username]/page.tsx
import api from "@/lib/api"
import { User, Blog, Post, Profile } from "@/models"
import PostCollection from "@/components/post-collection"
import MemberCard from "@/components/member-card"

import data from "./data"

interface Props {
  params: {
    username: string
  }
}

export default async function ProfilePage({ params }: Props) {
  const { profile, user, blogs, posts, likes } = await data(params.username)

  return (
    <main className="mx-auto my-8 flex flex-col items-center sm:flex-row sm:items-start px-2 w-full max-w-6xl gap-4 sm:gap-16">
      <MemberCard profile={profile} user={user} blogs={blogs} />

      <div>
        <div>
          <div className="py-4">
            <h1 className="font-semibold">Posts by {profile.displayName}</h1>
          </div>
          <PostCollection posts={posts} />
        </div>
        <div>
          <div className="py-4">
            <h1 className="font-semibold">Liked by {profile.displayName}</h1>
          </div>
          <PostCollection posts={likes} />
        </div>
      </div>
    </main>
  )
}

// frontend/src/routes/(pages)/profiles/[username]/+page.svelte
<script lang="ts">
	import ProfilePreview from "$lib/components/profile-preview.svelte"
	import Column from "$lib/layouts/column.svelte"
	import Entry from "$lib/components/entry-preview.svelte"

	import Json from "$lib/utils/json.svelte"

	const { data } = $props()
	const { profile, user, blogs, entries } = data
</script>

<svelte:head>
	<title>{profile.displayName}</title>
</svelte:head>

<div class="flex flex-col gap-3 mx-auto items-center">
	<ProfilePreview {profile} {user} />

	<Column>
		{#each entries as entry}
			<Entry {entry} omit={["author"]} />
		{/each}
	</Column>
</div>
