// site/components/Preview/Preview.tsx
import { PostMetadata } from "lib/post"
import Link from "components/Link"

export interface Props {
	postMetadata: PostMetadata
}

const Preview: React.FC<Props> = ({ postMetadata }) => {
	return (
		<div className="flex flex-col justify-start">
			<Link href={postMetadata.path}>
				<h2 className="font-medium">{postMetadata.title}</h2>
			</Link>
			<Link href={postMetadata.author.id} style="secondary">
				{postMetadata.author.name}
			</Link>
			<span className="text-sm">
				Updated: {new Date(postMetadata.updated).toLocaleDateString()}
			</span>
			<div className="flex flex-row flex-wrap gap-1">
				{postMetadata.tags.map((tag, index) => (
					<span
						key={index}
						className="text-xs text-white bg-neutral-800 rounded-md px-2 py-0.5"
					>
						{tag}
					</span>
				))}
			</div>
		</div>
	)
}

export default Preview

// frontend/src/lib/components/entry-preview/preview.svelte
<script lang="ts">
	import Card from "$lib/components/card/card.svelte"
</script>

<Card>
	<div class="flex flex-row">
		<div class="flex flex-col items-center justify-center">
			<slot name="likes" />
		</div>
		<div class="flex flex-col">
			<slot name="blog" />
			<slot name="title" />
			<div class="flex flex-row gap-1 items-center flex-wrap">
				<slot name="author" />
				<slot name="date" />
				<slot name="bookmark" />
			</div>
		</div>
	</div>
</Card>
