// apps/devy-frontend/src/routes/(pages)/[blog]/[...slug]/post-header.svelte
<script lang="ts">
	import { cva } from "cva"
	import type { Post } from "$lib/types"
	import Likes from "$lib/components/likes.svelte"
	import RelativeDate from "$lib/components/relative-date.svelte"
	import Bookmark from "$lib/components/bookmark.svelte"

	interface Props {
		post: Post
	}

	const { post }: Props = $props()

	let titleIsLong = $derived(post.title.length > 30)

	const title = cva("font-semibold text-stone-800 transition-all", {
		variants: {
			longTitle: {
				true: "text-4xl my-3",
				false: "text-5xl my-4"
			}
		}
	})
</script>

<div class="mx-auto my-8 w-full max-w-3xl transition-all">
	{#if post.coverImage}
		<div class="mb-6 rounded shadow-sm">
			<img
				src={post.coverImage || "/og-img.png"}
				alt={`Cover image for ${post.title}`}
				class="rounded"
			/>
		</div>
	{/if}

	<a href={`/${post.blogSlug}`} class="text-sm text-stone-600 hover:text-stone-950"
		>{post.blogName}</a
	>

	<h1 class={title({ longTitle: titleIsLong })}>
		{#if post.isDraft}
			<span class="font-medium text-yellow-500"> Draft: </span>
		{/if}
		{post.title}
	</h1>

	<div class="flex flex-row gap-1.5">
		<a
			href={`/profiles/${post.authorSlug}`}
			class="text-sm text-stone-600 transition-all hover:text-stone-950 dark:text-stone-400"
			>{post.authorName}</a
		>
		<div class="text-sm text-stone-700">
			<RelativeDate date={post.createdAt} />
		</div>
	</div>

	<div class="mt-4 flex flex-row">
		<Likes entryId={post.id} likeCount={post.likeCount} />
		<Bookmark postId={post.id} />
	</div>
</div>

// frontend/components/post/post-header/post-header.tsx
"use client"

import Likes from "@/components/post/likes"
import Link from "@/components/elements/link"
import RelativeDate from "@/components/utils/relative-date"

import { Post } from "@/models"

interface Props {
	post: Post
}

export default function PostHeader({ post }: Props) {
	return (
		<div className="mx-auto w-full max-w-3xl pb-6 sm:pb-12 flex flex-col gap-12">
			<div className="mx-auto w-full text-sm flex flex-row justify-between sm:gap-4">
				<Link
					href={{ pathname: `/${post.blogSlug}` }}
					variant={{ underline: false, styled: false }}
					className="text-neutral font-medium hover:text-neutral-1 hover:dark:text-neutral+1"
				>
					{post.blogName}
				</Link>
				<RelativeDate
					date={post.createdAt}
					className="text-neutral select-none"
				/>
			</div>

			<h1 className="text-4xl sm:text-6xl font-semibold text-neutral-1 dark:text-neutral+1">
				{post.title}
			</h1>

			<div className="mx-auto w-full text-sm flex flex-row justify-between sm:gap-4">
				<Link
					href={{ pathname: `/profiles/${post.authorUsername}` }}
					variant={{ underline: false, styled: false }}
					className="text-neutral font-medium hover:text-neutral-1 hover:dark:text-neutral+1"
				>
					{post.authorName}
				</Link>

				<Likes
					postId={post.id}
					title={post.title}
					initialCount={post.likes}
				/>
			</div>
		</div>
	)
}
