// frontend/app/[blog]/[post]/page.tsx
import Link from "@/components/link"
import RelativeDate from "@/components/relative-date"
import Markdown from "@/components/markdown"

import Post from "@/models/Post"
import api from "@/lib/api"

interface Props {
  params: {
    blog: string
    post: string
  }
}

export default async function Post({ params }: Props) {
  const post = await api.get<Post>(
    `/v1/blogs/${params.blog}/posts/${params.post}`,
    600
  )

  if (!post) return <div>Post not found</div>

  return (
    <main className="mx-auto my-4 flex flex-col px-2 py-12 w-full max-w-4xl gap-4 sm:gap-2">
      <div className="pb-12 flex flex-col gap-6">
        <div className="bg-zinc-800 text-sm flex items-center justify-start rounded-full gap-4">
          <Link href={`/${post.blogSlug}`} variant={{ underline: false }} className="text-neutral hover:text-neutral-1 hover:dark:text-neutral+1">
            {post.blogName}
          </Link>
          <RelativeDate date={post.createdAt} className="text-neutral" />
        </div>
        <h1 className="text-6xl font-semibold text-neutral-1 dark:text-neutral+1">
          {post.title}
        </h1>
        <div className="bg-zinc-800 text-sm flex items-center justify-start rounded-full gap-4">
          <Link
            href={`/profiles/${post.authorSlug}`}
            variant={{ underline: false }}
          >
            {post.authorName}
          </Link>
        </div>
      </div>

      <Markdown content={post.content} />
    </main>
  )
}

// site/src/routes/[blog]/[post]/+page.svelte
<script lang="ts">
	import type { PageData } from "./$types"
	import Markdown from "$lib/markdown/markdown.svelte"
	import Main from "$lib/layouts/main.svelte"
	import RelativeDate from "$lib/utils/relative-date.svelte"
	import H1 from "$lib/elements/h1.svelte"

	export let data: PageData
</script>

<Main>
	<div class="py-8 mx-auto w-full max-w-3xl flex flex-col gap-2">
		<a href={`/${data.props.entry.blogSlug}`} class="text-sm text-stone-500"
			>{data.props.entry.blogName}</a
		>
		<H1>{data.props.entry.title}</H1>
		<div class="flex flex-row gap-2">
			<a href={`/profiles/${data.props.entry.authorSlug}`} class="text-sm text-stone-500"
				>{data.props.entry.authorName}</a
			>
			<div class="text-sm dark:text-stone-300">
				<RelativeDate date={data.props.entry.createdAt} />
			</div>
		</div>
	</div>

	<article class="mx-auto w-full max-w-3xl">
		<Markdown source={data.props.entry.body} />
	</article>
</Main>
