// site/src/lib/post/preview/preview.svelte
<script lang="ts">
	import type { Post } from "$lib/types"
	import Json from "$lib/utils/json.svelte"
	import { Slash } from "radix-icons-svelte"
	import H2 from "$lib/element/h2.svelte"
	import Like from "$lib/post/like/like.svelte"
	import RelativeDate from "$lib/utils/relative-date.svelte"

	export let post: Post
	const { title, slug, authorName, authorUsername, blogName, blogSlug, createdAt } = post
</script>

<div class="flex flex-col">
	<div class="flex flex-row gap-0.5 text-xs">
		<a href={`/profiles/${authorUsername}`} class="text-zinc-600">{authorName}</a>
		<Slash class="text-zinc-500" />
		<a href={"#"} class="text-zinc-600">{blogName}</a>
	</div>
	<div class="font-medium">
		<H2><a href={`/${blogSlug}/${slug}`}>{title}</a></H2>
	</div>
	<div class="text-xs"><RelativeDate date={createdAt} /></div>
</div>

// frontend/components/Preview/Preview.tsx
"use client"

import { HeartIcon, HeartFilledIcon } from "@radix-ui/react-icons"

import Post from "@/models/Post"
import { Button, Link } from "@/components/elements"
import Like from "@/components/Like"

import api from "@/lib/api"
import { SessionStatus } from "@/lib/auth"

interface Props extends Post {
	session: SessionStatus
	isLiked: boolean
}

export default function Preview({
	id,
	title,
	slug,
	blogSlug,
	authorName,
	authorSlug,
	blogName,
	likes,
	session,
	isLiked,
}: Props) {
	const user = "e2f0fa7e-4517-4ac8-bbc6-73067d3feed4"

	const like = async () => {
		console.log("like")
		await api.post(`/posts/${id}/likes`, 10, user)
	}

	return (
		<section className="flex flex-row gap-2 items-start">
			<div className="flex flex-col items-start gap-1">
				<Like
					active={session === "logged-in"}
					isLiked={isLiked}
					count={likes}
				/>
			</div>

			<div className="flex flex-row items-start gap-1">
				<div className="flex flex-col gap-1">
					<Link
						href={`${blogSlug}/${slug}`}
						className="font-medium text-zinc-50"
					>
						{title}
					</Link>

					<div className="mb-2 flex flex-row gap-2 items-baseline text-sm">
						<Link href={`/profiles/${authorSlug}`}>
							{authorName}
						</Link>
						<Link href={`/${blogSlug}`}>{blogName}</Link>
					</div>
				</div>
			</div>
		</section>
	)
}
