// frontend/app/[blog]/page.tsx
import { Blog, Post } from "@/models"
import api from "@/lib/api"

import BlogPosts from "@/components/blog-posts"
import data from "./data"

interface Props {
  params: {
    blog: string
  }
}

export default async function BlogPage({ params }: Props) {
  const { blog, posts } = await data(params.blog)

  return (
    <>
      <main className="mx-auto my-4 flex flex-col px-2 w-full max-w-6xl gap-12">
        <header>
          <h1 className="text-4xl font-semibold">{blog.name}</h1>
        </header>
        <section className="flex flex-col gap-2">
          <h2 className="font-medium text-xl">Posts</h2>
          <BlogPosts posts={posts} />
        </section>
      </main>
    </>
  )
}

// frontend/src/routes/(pages)/[blog]/+page.svelte
<script lang="ts">
	import Header from "./header.svelte"
	import Entries from "./entries.svelte"
	import Json from "$lib/utils/json.svelte"

	const { data } = $props()
	const { blog, entries, isUserFollowing } = data
</script>

<svelte:head>
	<title>{blog.name}</title>
</svelte:head>

<div class="mx-auto max-w-2xl">
	<Header {blog} {isUserFollowing} />
	<div class="flex flex-col items-center">
		<Entries {entries} />
	</div>
</div>
