// frontend/src/routes/(pages)/header.svelte
<script lang="ts">
	import Home from "$lib/components/home.svelte"
	import Main from "$lib/layouts/main.svelte"
	import Navigation from "./navigation.svelte"
</script>

<div class="border-b border-b-stone-200 dark:border-b-zinc-700 mb-4">
	<Main>
		<header class="pt-2 pb-2 flex flex-row gap-3 justify-between items-center">
			<Home />
			<Navigation />
		</header>
	</Main>
</div>

// frontend/components/header/header.tsx
import Home from "./home"
import Nav from "./nav"

export default function Header() {
	return (
		<header className="border-b border-b-neutral+1 dark:border-b-neutral-1">
			<div className="mx-auto max-w-6xl px-3 py-3 flex flex-row justify-between items-center">
				<Home />
				<Nav />
			</div>
		</header>
	)
}
