// frontend/app/footer.tsx
import Link from "@/components/link"
import Logomark from "@/components/logomark"

export default function Footer() {
  return (
    <footer className="w-full bg-neutral+2 dark:bg-neutral-3 transition-all">
      <div className="mx-auto max-w-6xl px-3 pt-8 pb-44">
        <div className="w-full sm:w-56 pb-2 border-b border-b-neutral+1 dark:border-b-neutral-1 flex flex-row gap-2 items-baseline">
          <Link href="/" variant={{ underline: false }}>
            <Logomark />
          </Link>
          <span className="text-xs font-medium px-2 py-0.5 rounded-full text-neutral-1 bg-neutral+1 dark:text-neutral+2 dark:bg-neutral-1 select-none">
            Preview
          </span>
        </div>

        <div className="pt-2 flex flex-col sm:flex-row gap-12 text-sm text-zinc-300">
          <section className="w-full sm:w-56 flex flex-col gap-4">
            <p>
              Devy is an open source platform for people to publish blog posts
              in markdown from their GitHub repositories.{" "}
            </p>
            <p>Thank you for checking it out.</p>
            <span className="self-end">
              &#8212;{" "}
              <Link
                href="https://thomaseckert.dev"
                variant={{ underline: true }}
              >
                Thomas Eckert
              </Link>
            </span>
          </section>

          <section className="flex flex-row font-medium sm:flex-col gap-4 sm:gap-1 items-start">
            <Link href="/changelog">Changelog</Link>
            <Link href="https://github.com/t-eckert/devy">Repo</Link>
            <Link href="https://github.com/t-eckert/devy/issues/new/choose">
              Open an issue
            </Link>
          </section>
        </div>
      </div>
    </footer>
  )
}

// site/src/lib/footer/footer.svelte
<footer class="w-full transition-all pb-12">
	<div class="mx-auto max-w-6xl p-3 pb-12 bg-zinc-900/40 rounded-xl">
		<div
			class="w-full sm:w-56 pb-2 border-b border-b-neutral+1 dark:border-b-neutral-1 flex flex-row gap-2 items-baseline"
		>
			<div class="flex flex-row gap-2 items-baseline">
				<a href="/" class="px-0.5 -ml-0.5">Devy</a>
				<span
					class="text-xs font-medium px-2 py-0.5 rounded-full text-zinc-300 bg-zinc-700 dark:text-zinc-300 dark:bg-zinc-700 select-none"
					>Preview</span
				>
			</div>
		</div>
		<div class="pt-2 flex flex-col sm:flex-row gap-12 text-sm text-zinc-300">
			<section class="w-full sm:w-56 flex flex-col gap-4">
				<p>
					Devy is an open source platform for people to publish blog posts in markdown from their
					GitHub repositories.{' '}
				</p>
				<p>Thank you for checking it out.</p>
				<span class="self-end">
					&#8212;{' '}
					<a href="https://thomaseckert.dev">Thomas Eckert</a>
				</span>
			</section>

			<section class="flex flex-row font-medium sm:flex-col gap-4 sm:gap-1 items-start">
				<a href="/changelog"> Changelog </a>
				<a href="https://github.com/t-eckert/devy"> Repo </a>
				<a href="https://github.com/t-eckert/devy/issues/new/choose"> Open an issue </a>
			</section>
		</div>
	</div>
</footer>
